node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

dashboard {
  listeners.http {
    bind = 18083
  }
}

zones.default {
  flapping_detect {
    enable = false
  }
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
  max_conn_rate = 10000
  tcp_options {
    backlog = 10000
    nodelay = true
    reuseaddr = true
  }
}